#######################################################
# 
# NivelSitio.py
# Python implementation of the Class NivelSitio
# Generated by Enterprise Architect
# Created on:      22-mar.-2019 9:14:34
# Original author: acfde
# 
#######################################################


class NivelSitio:
    pass