/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 27-mar.-2019 11:44:55 				*/
/*  DBMS       : SQLite 								*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS 'Proyecto'
;

/* Create Tables with Primary and Foreign Keys, Check and Unique Constraints */

CREATE TABLE 'Proyecto'
(
	'Cantofertantes' varchar NULL,
	'Cantproyectosproponenete' varchar NULL,
	'Descripcion' varchar NULL,
	'Habilidades' varchar NULL,
	'Monedavalor' varchar NULL,
	'Nomproponente' varchar NULL,
	'Numhabilidades' varchar NULL,
	'Numpreguntas' varchar NULL,
	'Ofertamax' varchar NULL,
	'Ofertamin' varchar NULL,
	'Ofertapromedio' varchar NULL,
	'Paisproponente' varchar NULL,
	'Proyectospagadosproponentes' varchar NULL,
	'RequisitosEspeciales' varchar NULL,
	'Valormax' varchar NULL,
	'Valormin' varchar NULL,
	'ProyectoID' varchar NOT NULL PRIMARY KEY,
	'MensajeID' varchar NULL,
	'OfertaID' varchar NULL,
	CONSTRAINT 'FK_Proyecto_Mensaje' FOREIGN KEY ('MensajeID') REFERENCES 'Mensaje' ('MensajeID') ON DELETE No Action ON UPDATE No Action,
	CONSTRAINT 'FK_Proyecto_Oferta' FOREIGN KEY ('OfertaID') REFERENCES 'Oferta' ('OfertaID') ON DELETE No Action ON UPDATE No Action
)
;
