import tkinter as tk
from tkinter import ttk as ttk
from tkinter import messagebox
#from tkintertable.Tables import TableCanvas
from tkintertable import TableCanvas, TableModel
import sqlite3 

#######################################################
# 
# Sitio.py
# Python implementation of the Class Sitio
# Generated by Enterprise Architect
# Created on:      22-mar.-2019 8:06:16
# Original author: acfde
# 
####################################################################################
#import Oferta
#import Inscripcion
import enumeradores
import LabelInput as li
from  sitio_backend import *
from proyecto import Proyecto
import datetime
from StartDriveApi import ViewDrive, main

class Sitio(tk.LabelFrame):
    """Clase para definir los sitios
    """
    #m_Oferta= Oferta()

    #m_Inscripcion= Inscripcion()

    #m_Lenguaje= Lenguaje()

    cantsitios = 0
    tempsitio={}
    tempidiomas=[]
    temptipos=[]


    def __init__(self, raiz,nombre,url,lenguajes,tipositio,cantnivel):
        super(Sitio,self).__init__()
        Sitio.cantsitios+=1
        self.nomsitio=nombre
        self.url=url
        self.lenguajes=lenguajes # lista de lenguajes posibles
        self.cantnivel=cantnivel # cantidades de nivel que se tienen
        self.nomnivel=[]         # nombre de cada nivel
        self.costoXnivel=[]       # costo en punts de cada nivel
        self.ofertasXnivel=[]     # cantidad de ofertas x cada nivel

        self.cantplansuscrip=0
        self.nomplansuscrip=[]
        self.costoplansuscrip=[]
        self.ofetraplansuscrip=[]

        self.costoXofertas =0
        self.tipositio=tipositio
    
   
        self.sitio={'idsitio':tk.IntVar() ,"nomsitio":tk.StringVar(),"url":tk.StringVar(),"pais":tk.StringVar(),
        'creacion':tk.StringVar(), 'nivelesdemerito':tk.IntVar(), 'nivelesmembresia':tk.IntVar(),'urlproy': tk.StringVar(),
        'nombusq': tk.StringVar(),'clavebusq':tk.StringVar(),'notas':tk.StringVar()}

        self.sitioval={'idsitio':9 ,"nomsitio":'',"url":"www.XXXXXX.com","pais":'USA',
        'creacion':'01/01/2019', 'nivelesdemerito':0, 'nivelesmembresia':1,'urlproy': "www.XXXXXX.com/projects",
        'nombusq': "raulrfa", "clavebusq":"Karpov75%",'notas':""}

        
        """ 
        for value in self.sitio:
            if type(self.sitio.values)==type(tk.StringVar()):
                self.sitio.values=StringVar.set('')
            else:
                self.sitio.values=tk.IntVar.set(0)"""
        #print (list(self.sitio.keys()))
        #print(list(self.sitio.values()))

        self.sitidi={"idsitio":tk.IntVar(),"ididioma":tk.IntVar()}
        
        self.show_sitio_frame()
        self.muestrasitios(editsitiosdb())
        self.proy=Proyecto(raiz,"",-1)
        self.proy.muestraproyectos(self.frlistproy,editprelproyectosdb(0))
       
        self.muestra_but_ctrl()
        self.muestra_checkbut()
        self.muestra_edi()

    def show_sitio_frame(self):
        #self.graf = tk.LabelFrame
        #self.graf.configure(self,text='Edicion de Sitios',bg='gray')
        self.master=raiz

        #muestra las frames de la lista de sitio y los botnes        
        self.frgridsit = tk.LabelFrame(self,bg='gray',text='Sitios')
        self.frgridsit.pack(side=tk.LEFT, fill=tk.Y)
        self.frbutsit = tk.Frame(self,bg='gray')
        self.frbutsit.pack(side=tk.LEFT)   
        self.frlistsit = tk.Frame(self.frgridsit,bg='cyan')
        self.frlistsit.pack(side=tk.TOP)
        self.frlistproy = tk.Frame(self.frgridsit,bg='lightyellow')
        self.frlistproy.pack(side=tk.TOP)
        
       
        self.fredit= tk.Frame(self,bg="cyan")
        self.fredit.pack(side=tk.LEFT, fill=tk.Y, expand=1)   
        self.frcheckbut= tk.Frame(self,bg='gray')
        self.frcheckbut.pack(side=tk.LEFT)      
        self.frbut=tk.Frame(self,bg='yellow')
        self.pack(side=tk.LEFT)
        self.frbutidi =tk.LabelFrame(self.frcheckbut,bg='blue',text='Idiomas',width=25)
        self.frbutidi.pack(side=tk.TOP,fill=tk.Y)
        
        self.frbutip =tk.LabelFrame(self.frcheckbut,bg='lightyellow',text="Tipos", width=25)
        self.frbutip.pack(side=tk.TOP,fill=tk.Y)

        self.frbutarea =tk.LabelFrame(self.frcheckbut,bg='lightgreen',text="Area de Trabajo", width=25)
        self.frbutarea.pack(side=tk.TOP,fill=tk.Y)
        self.frbuthab =tk.LabelFrame(self.frcheckbut,bg='lightyellow',text="Habilidades", width=25)
        self.frbuthab.pack(side=tk.TOP,fill=tk.Y)
        self.frediprelproy =tk.LabelFrame(self,bg='lightyellow',text="Proyecto y Oferta Preliminar", width=25)
        self.frediprelproy.pack(side=tk.LEFT,fill=tk.Y)
        self.frediproy=tk.LabelFrame(self,bg='lightyellow',text="Proyecto y Oferta", width=25)
        self.frediproy.pack(side=tk.LEFT,fill=tk.Y)

        
        self.freditbut= tk.Frame(self.fredit,bg='gray')
        #self.freditbut.pack()
        
        self.cb_idi=[] # lista de check but
        self.iv_idi=[] # lista de IntVar
        self.cb_tip = [] # lista de check but para tipos
        self.iv_tip = [] # lista de IntVar
        self.cb_area =[] # areas de trabajo
        self.iv_area =[] # areas de trabajo
        self.cb_hab =[]  # habilidades
        self.iv_hab =[] # areas de trabajo
       
       
        

        
   

    def muestra_checkbut(self):
        for leng in range(1,1+len(enumeradores.Idiomas)):
            self.iv_idi.append(tk.IntVar())
            self.cb_idi.append(ttk.Checkbutton(self.frbutidi, name=str(leng) ,text=enumeradores.Idiomas(leng).name
            , variable=self.iv_idi[leng-1], command=self.cbclick))
            self.cb_idi[leng-1].state(['!alternate'])
            self.cb_idi[leng-1].grid(row=leng,column=0,sticky=tk.W+tk.E)
        for leng in range(1,1+len(enumeradores.TipoProyecto)):
            self.iv_tip.append(tk.IntVar())
            self.cb_tip.append(ttk.Checkbutton(self.frbutip, name=str(leng) ,text=enumeradores.TipoProyecto(leng).name
            , variable=self.iv_tip[leng-1], command=self.cbclick))
            self.cb_tip[leng-1].state(['!alternate'])
            self.cb_tip[leng-1].grid(row=leng,column=0, sticky=tk.W+tk.E)
        for leng in range(1,1+len(enumeradores.AreasTrab)):
            self.iv_area.append(tk.IntVar())
            self.cb_area.append(ttk.Checkbutton(self.frbutarea, name=str(leng) ,text=enumeradores.AreasTrab(leng).name
            , variable=self.iv_area[leng-1], command=self.cbclick))
            self.cb_area[leng-1].state(['!alternate'])
            self.cb_area[leng-1].grid(row=leng,column=0,sticky=tk.W+tk.E)
        for leng in range(1,1+len(enumeradores.Habilidades)):
            self.iv_hab.append(tk.IntVar())
            self.cb_hab.append(ttk.Checkbutton(self.frbuthab, name=str(leng) ,text=enumeradores.Habilidades(leng).name
            , variable=self.iv_hab[leng-1], command=self.cbclick))
            self.cb_hab[leng-1].state(['!alternate'])
            self.cb_hab[leng-1].grid(row=leng,column=0, sticky=tk.W+tk.E)
    
    def muestra_edi(self):
       #self.sitio['nomsitio'].set('bbbb')
       li.LabelInput(self.fredit,'Nombre del Sitio', input_var=self.sitio['nomsitio']).grid(row=1, column=1)
       li.LabelInput(self.fredit,'Url', input_var=self.sitio['url']).grid(row=2, column=1)
       li.LabelInput(self.fredit,"País de Origen",input_class=ttk.Combobox, input_var=self.sitio['pais'],
       input_args={"values": ["Argentina", "Australia", "USA","Francia", "Alemania"]}).grid(row=3,column=1)
       li.LabelInput(self.fredit,'Niveles de Merito', input_var=self.sitio['nivelesdemerito']).grid(row=4,column=1)
       li.LabelInput(self.fredit,"Nivel de Suscripcion",input_class=ttk.Combobox, input_var=self.sitio['nivelesmembresia'],
       input_args={"values": ["0", "1", "2","3", "4"]}).grid(row=5,column=1)
   
       li.LabelInput(self.fredit,'URL de Busquedad de Proyectos', input_var=self.sitio['urlproy']).grid(row=6,column=1)
       li.LabelInput(self.fredit,'Nombre Buquedad', input_var=self.sitio['nombusq']).grid(row=7,column=1)
       li.LabelInput(self.fredit,'Clave de Busquedad', input_var=self.sitio['clavebusq']).grid(row=8,column=1)
       li.LabelInput(self.fredit,'Fecha Creacion', input_var=self.sitio['creacion']).grid(row=9,column=1)
       self.sitio['notas'].set(li.LabelInput(self.fredit,'Notas', input_class=tk.Text,input_args={"height": 10,"width": 25}).grid(row=10,column=1))
       
       
  
       

    
    def show(self):
        pass
    def exit(self):
        pass

    def selectItem(self, event, arg):   # como argumento se pasa la lista de sitios
        curItem = self.listBox.focus()
        idsitio=self.listBox.item(curItem)['values'][0]
        fila=arg[int(curItem)-1]  # los enumeradores y bd el primer rticulo tiene id 1
        f=0
        for val in self.sitio.values():
            val.set(fila[f])
            f+=1
        setIdioma=setTipos=setArea=setHab=[]
        setIdioma=muchosUnsitio(idsitio,enumeradores.Idiomas,setIdioma,0) 
        setTipos=muchosUnsitio(idsitio,enumeradores.TipoProyecto,setTipos,0) 
        setArea=muchosUnsitio(idsitio,enumeradores.AreasTrab,setArea,0) 
        setHab=muchosUnsitio(idsitio,enumeradores.Habilidades,setHab,0) 

        for i in range(len(self.cb_idi)):
            if i in setIdioma: 
                self.iv_idi[i].set(1)
            else:
                self.iv_idi[i].set(0)                
        for i in range(len(self.cb_tip)):
            if i in setTipos: 
                self.iv_tip[i].set(1)
            else:
                self.iv_tip[i].set(0)  
        for i in range(len(self.cb_area)):
            if i in setArea: 
                self.iv_area[i].set(1)
            else:
                self.iv_area[i].set(0)  
        for i in range(len(self.cb_hab)):
            if i in setHab:
                self.iv_hab[i].set(1)
            else:
                self.iv_hab[i].set(0)  
        self.mostrarproyectos(ord)
           
    
    def muestrasitios(self,listasitios):
         
        self.TitlistBox = tk.Label(self.frlistsit, text="Sitios Registrados", font=("Arial",16)).grid(row=0, columnspan=11)
        # create Treeview with 3 columns
        cols = ('Orden', 'Nombre', 'URL', 'País','Çreación','NivMerito', 'NivMem','URLProy','','','')
       
        self.listBox = ttk.Treeview(self.frlistsit, columns=cols, displaycolumns=(0,1,2,3,4,5,6,7), padding=3, show='headings')
        #listBox[columns]=('size',width=8,anchor='center')
        for i, (id,name,url,pais,crea,nivmer,nivmemb,urlp,c1,c2,c3) in enumerate(listasitios, start=1):
            self.listBox.insert("", "end", i,values=(id, name,url,crea,nivmer,nivmemb,urlp))
        # set column headings
        for col in cols:
            if  cols.index(col) == 0:
                self.listBox.column(col,width=10,anchor=tk.W)
            elif cols.index(col) in (5,6):
                self.listBox.column(col,width=35,anchor=tk.W)
            else:
                self.listBox.column(col,width=100,anchor=tk.W)
            
            self.listBox.heading(col, text=col)    
        self.listBox.grid(row=1, column=0, columnspan=11)
        #self.listBox.bind('<Button-1>', self.selectItem)
        self.listBox.bind('<<TreeviewSelect>>', lambda event, arg=listasitios: self.selectItem(event,arg))

    


        #for col in self.listBox.columns:
        #    self.sitio[curItem.col.name].set(curItem.col.value)
          

    def muestra_but_ctrl(self):
        self.butnuevo= tk.Button(self.frbutsit, bg='cyan',text= 'Nuevo',command=self.nuevo)
        self.butnuevo.pack(side=tk.TOP, pady=10)
        self.buteditar= tk.Button(self.frbutsit, bg='cyan',text= 'Editar',command=self.editar)
        self.buteditar.pack(side=tk.TOP, pady=10)
        self.butcopiar= tk.Button(self.frbutsit, bg='cyan',text= ' Copiar',command=self.copiar)
        self.butcopiar.pack(side=tk.TOP, pady=10)
        self.butlimpiar= tk.Button(self.frbutsit, bg='cyan',text= ' Limpiar',command=self.limpiar)
        self.butlimpiar.pack(side=tk.TOP, pady=10) 
        self.butlborrar= tk.Button(self.frbutsit, bg='cyan',text= 'Borrar',command=self.borrar)
        self.butlborrar.pack(side=tk.TOP, pady=10) 
        self.butsalvar= tk.Button(self.frbutsit, bg='cyan',text= ' Salvar',command=self.salvar)
        self.butsalvar.pack(side=tk.TOP, pady=10) 
        self.butestad= tk.Button(self.frbutsit, bg='orange',text= ' Estadisticas',command=self.estadistica)
        self.butestad.pack(side=tk.TOP, pady=10) 
        self.butbuscar= tk.Button(self.frbutsit, bg='orange',text= ' Buscar',command=self.buscar)
        self.butbuscar.pack(side=tk.TOP, pady=10) 
        self.butanalizar= tk.Button(self.frbutsit,bg='orange', text= ' Analizar',command=self.analizar)
        self.butanalizar.pack(side=tk.TOP, pady=10) 
        self.butmostrarproyectos= tk.Button(self.frbutsit,bg='yellow', text= ' Actualizar',command=self.mostrarproyectos)
        self.butmostrarproyectos.pack(side=tk.TOP, pady=10) 
        self.butprelproy= tk.Button(self.frbutsit,bg='yellow', text= 'Preliminar',command=self.creanuevoproyecto)
        self.butprelproy.pack(side=tk.TOP, pady=10) 
        self.butsalvarprelproy= tk.Button(self.frbutsit, bg='yellow',text= 'Salvar Preliminar')
        self.butsalvarprelproy.pack(side=tk.TOP, pady=10) 
        self.butprelofer= tk.Button(self.frbutsit, bg='yellow',text= ' Proyecto')
        self.butprelofer.pack(side=tk.TOP, pady=10)
        self.butmostrarofertas= tk.Button(self.frbutsit,bg='magenta', text= 'Ofertas',command=self.mostrarofertas)
        self.butmostrarofertas.pack(side=tk.TOP, pady=10)
        if self.proy==None:
            self.butsalvarprelproy.state=tk.DISABLED
            self.butprelofer.state=tk.DISABLED
        

    def creanuevoproyecto(self):
        self.proy=Proyecto(self.frediprelproy,self.nomsitio,self.sitio['idsitio'].get())
        self.butsalvarprelproy.state=tk.NORMAL
        self.butsalvarprelproy.bind('<Button-1>',self.proy.salvarprelproy)

        self.butprelofer.state=tk.NORMAL
        self.butprelofer.bind('<Button-1>',self.proy.muestra_proy)
        self.proy.newprelproy()
        

    def nuevo(self):
        self.limpiar()
        for key,val in self.sitio.items():
            print(key,'Defecto: ',self.sitioval[key])
            val.set(self.sitioval[key]) # toma el valor por defecto
        last=nuevositiodb()
        self.sitioval['idsitio']=last
        print(self.sitioval['idsitio'])
        self.muestrasitios(self,editsitiosdb())
        self.listBox.selection_set(last-1)
        Sitio.cantsitios+=1


        

       
         
       
        
                
    def editar(self):
        line= self.listBox.curselection()[0]+1
        print(line)
        db = sqlite3.connect('freebd.db')
        curs = db.cursor()
        # En el filtro debiera ser distinct en el body todos
        query =" SELECT * FROM  sitios where idsitio={} ".format(line)
        # query = query + " and tema = "+ 
        curs.execute(query)
        lista=curs.fetchall()
        print(lista)
        i=0
        print('Lista y Dicc',len(lista[0]),len(self.sitio))
        for val in self.sitio.values():
            if i==range(len(lista[0])): break
            val.set(lista[0][i])
            print(i,  "valor es ", lista[0][i])
            i+=1

        query= " SELECT * FROM  sitioidioma where idsitio={} ".format(line)
        curs.execute(query)
        lista=curs.fetchall()
        print('idioma',lista)
        for sitidi in lista:
            print(self.cb_idi[sitidi[1]-1].state())
            self.iv_idi[sitidi[1]-1].set(1)
        
        query= " SELECT * FROM  sitiostipo where idsitio={} ".format(line)
        curs.execute(query)
        lista=curs.fetchall()
        print('tipo',lista)
        for sitidi in lista:
            self.iv_tip[sitidi[1]-1].set(1)
        
        


    def mostrarproyectos(self,ord):
        if self.proy==None:
            self.proy.muestraproyectos(self.frlistproy, editprelproyectosdb(0) ) 
        elif self.proy.Master.get()==True: 
            # el defecto es false, se muestran todos los proyectos
            self.proy.llenagrid(editprelproyectosdb(ord))


    def copiar(self):
        sitio.tempsitio=self.sitio
        sitio.tempidiomas=self.cb_idi
        sitio.temptipos=self.cb_tip

    


        

    def salvar(self):
        lista=[]
        listaerror =[]
        for sel in self.sitio.values():
            try: lista.append(sel.get())
            except:
                listaerror.append(type(sel))
        print('lerror: ',listaerror)
        print(lista)
        id=updatesitio(lista)
        if id!=lista[0]: # no hay problemas se retorno el mismo rowguid
            messagebox.showerror('Error','No se pudo salvar el sitio')
            return
        else:
            self.listBox.item(self.listBox.focus(),value=lista)
        setIdioma=set()
        setTipos=set()
        setArea=set()
        setHab=set()
        
        for i in range(len(self.cb_idi)):
            if self.cb_idi[i].instate(['selected']) : setIdioma.add(i) 
        for i in range(len(self.cb_tip)):
            if self.cb_tip[i].instate(['selected']) : setTipos.add(i) 
        for i in range(len(self.cb_area)):
            if self.cb_area[i].instate(['selected']) : setArea.add(i) 
        for i in range(len(self.cb_hab)):
            if self.cb_hab[i].instate(['selected']) : setHab.add(i)
        muchosUnsitio(id,enumeradores.Idiomas,setIdioma,1) 
        muchosUnsitio(id,enumeradores.TipoProyecto,setTipos,1) 
        muchosUnsitio(id,enumeradores.AreasTrab,setArea,1) 
        muchosUnsitio(id,enumeradores.Habilidades,setHab,1) 
  
    def limpiar(self):
        for leng in range(1,1+len(enumeradores.Idiomas)):
            self.cb_idi[leng-1].state(['!alternate'])
        for leng in range(1,1+len(enumeradores.TipoProyecto)):
            self.cb_tip[leng-1].state(['!alternate'])
        for leng in range(1,1+len(enumeradores.AreasTrab)):
            self.cb_area[leng-1].state(['!alternate'])
        for leng in range(1,1+len(enumeradores.Habilidades)):
            self.cb_hab[leng-1].state(['!alternate'])

        

        for val in self.sitio.values():
            if type(val)==tk.IntVar:
                val.set(0)
            else:
                val.set('')
                
    def borrar(self):
        ind= self.listBox.focus() 
        line=self.listBox.index(ind) 
        messagebox.answer = messagebox.askyesnocancel("Atención!","¿Desea borrar el sitio no. {}".format(line))
        if messagebox.answer:
            last=deletesitiodb(line)
            Sitio.cantsitios=-1
            self.listBox.delete(ind)
            self.listBox.selection_set(self.listBox.item(last))

    def estadistica(self):
        messagebox.showinfo('Estadisticas', 'Cantidad de sitios: {}'.format(Sitio.cantsitios))

    def mostrarofertas(self):
        raiz2 = tk.Tk()
        #TODO pr que no reconoce las Control booleanas cdo de llama a una pagina inde[pendiente
        gd=ViewDrive(raiz,main(),1)
        #gd=ViewDrive(raiz,None,1)
        gd.gui_butmenu()
        gd.gui_oferta_guardada()
        #gd.cambiartit()
        raiz2.mainloop()

    def buscar(self):
        pass
    def analizar(self):
        pass
    def cbclick(self):
        pass

    
  

if __name__ == '__main__':
    raiz = tk.Tk()
    b=Sitio(raiz,'Workana','workana.com',[],[],3)
    #b.muestra_checkbut()
    raiz.mainloop()    